
#define STEP 0.2
#define LEFT 1
#define RIGHT -1
#define FORWARD 1
#define BACK -1
#define X 0
#define Y 1
#define Z 2
#define ENDFORWARD 5.0
#define ENDBACK 16.0
#define ENDRIGHT 5.8
#define ENDLEFT -5.8
#define PI 3.14159265
#define PLAYERMODE 0
#define BALLMODE 1
#define OVERVIEWMODE 2
#define PLAYER1 0
#define PLAYER2 1
#define REGULARTHROW 0
#define REPLAYTHROW 1
#define HARD 0.3
#define MEDIUM 0.2
#define EASY 0.1
